site_name: immunomind.
site_url: https://immunarch.com
repo_url: https://github.com/immunomind/immunarch
repo_name: immunomind/immunarch

docs_dir: docs/source

nav:
  - Getting started:
    - Home: index.md
    - intro/installation.md
    - intro/quick_start.md
  - Concepts:
    - concepts/glossary.md
    - Basics:
      - concepts/basics/overview.md
      - concepts/basics/data_units.md
      - concepts/basics/aggregation.md
      - concepts/basics/immutability.md
    - Workflow:
      - concepts/workflow/phase_ingestion.md
      - concepts/workflow/phase_transformation.md
    # - Analysis:
      # - concepts/receptor-level + family of functions
      # - concepts/repertoire-level
      # - concepts/barcode-level
      # - concepts/biomarker_discovery
      # - concepts/feature_engineering
    # - Internals:
      # - concepts/duckdb-arrow-parquet.md
      # - concepts/extend_immunarch.md
      # - concepts/data_engineering.md
  - User guide:
    # - IO:
    #   - Ingesting repertoire files: guides/ingest-repertoires.md
    #   - Metadata merge: guides/ingest-metadata.md
    #   - Preprocessing and postprocessing: guides/preprocessing.md
    #   - guides/snapshots.md
    #   - guides/output.md
    # - Transformations:
    #   - Filter: guides/output.md
    #   - Annotate: guides/output.md
    # - Repertoire-level analysis:
    #   - guides/installation.md
    #   - guides/data_loading.md
    # - Receptor-level analysis:
    #   - guides/data_loading.md
    # - Biomarker discovery:
    #   - guides/biomarkers.md
    # - Feature engineering:
    #   - guides/features.md
    - guides/faq.md
  - How-to:
    - Input:
      - Bulk AIRR-C: howto/read_airr_bulk.md
      - Single-cell AIRR-C: howto/read_airr_sc.md
      # - 10x Genomics, single-chain: howto/read_10x_single.md
      # - 10x Genomics, paired-chain: howto/read_10x_paired.md
    #
    # URGENT NOW
    #
    #   - howto/metadata_input_files.qmd # Load immune repertoire files to R (and Python) using metadata
    #   - howto/metadata_sample_info.qmd # Add sample information using metadata

    #
    # NEXT STEP
    #
    #   - howto/read_mixcr_bulk.md
    #   - howto/read_mixcr_sc.md
    #   - howto/read_bd.md
    #   - howto/read_dandelion.md
    #   - howto/read_immcantation.md
    #   - howto/read_parsebio.md
    #   - howto/read_trust4.md
    #   - howto/read_wat3r.md
      - Import old `immunarch` data: howto/immunarch_import.md
    - Performance:
      # - howto/snapshots.qmd
      - howto/no_threads.md
  - Tutorials:
      - tutorials/single_cell.qmd
      - tutorials/migration.md
  - API reference:
      - api/reference.md
  # - Support:
      # - How to get help: community/support.md # links to GitHub Issues, Discord, etc.
      # - Translations: support/translation.md
      # - Contributing guide: community/contributing.md
      # - Code of conduct: community/code-of-conduct.md
      # - Authors

theme:
  name: material
  logo: assets/phoenix_cl2.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: blue grey
      accent: amber

    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: indigo
      accent: blue
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.tabs.link
    - content.code.copy
    - navigation.sections
    - navigation.expand

markdown_extensions:
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index:     !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables

plugins:
  - mkquartodocs
  - search:
      lang: en
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: "🌚 English"
          build: true
        - locale: zh
          name: "🇨🇳 简体中文"
          # build: true
          build: false
        - locale: ko
          name: "🇰🇷 한국어"
          # build: true
          build: false
        - locale: ja
          name: "🇯🇵 日本語"
          # build: true
          build: false
        - locale: es
          name: "🇪🇸 Español"
          # build: true
          build: false
        - locale: pt-BR
          name: "🇧🇷 Português (BR)"
          # build: true
          build: false

hooks:
  - hooks.py

extra_css:
  - stylesheets/extra.css