site_name: immunomind.
site_url: https://immunarch.com
repo_url: https://github.com/immunomind/immunarch
repo_name: immunomind/immunarch

docs_dir: docs/source

nav:
  - Getting started:
    - What is immunarch + immundata?: intro/introduction.md
    # - Installation: intro/installation.md
    # - Quick start: intro/quick-start.md
  - Concepts:
    - Basics:
      - concepts/basics.md
      - concepts/data-units.md
      - concepts/aggregation.md
      - concepts/immutability.md
    - Workflow:
      - concepts/phase_ingestion.md
      - concepts/phase_transformation.md
    # - Analysis:
      # - concepts/receptor-level + family of functions
      # - concepts/repertoire-level
      # - concepts/barcode-level
      # - concepts/biomarker_discovery
      # - concepts/feature_engineering
    # - Internals:
      # - concepts/duckdb-arrow-parquet.md
      # - concepts/extend_immunarch.md
      # - concepts/data_engineering.md
  - User guide:
    # - IO:
      # - Ingesting repertoire files: guides/ingest-repertoires.md
      # - Metadata merge: guides/ingest-metadata.md
      # - Preprocessing and postprocessing: guides/preprocessing.md
      # - guides/output.md
    # - Transformations:
      # - Filter: guides/output.md
      # - Annotate: guides/output.md
    - Repertoire-level analysis:
      - guides/installation.md
      - guides/data-loading.md
    - Receptor-level analysis:
      - guides/data-loading.md
    # - Use cases:
      # - guides/bulk.md
      # - guides/paired-chain.md
      # - guides/single-cell.md
    - guides/faq.md
  # - How to:
  #     - tutorials/single-cell.qmd
  - Tutorials:
      - tutorials/single-cell.qmd
  - API reference:
      - api/reference.md
  # - Community & support:
      # - How to get help: community/support.md # links to GitHub Issues, Discord, etc.
      # - Contributing guide: community/contributing.md
      # - Code of conduct: community/code-of-conduct.md
  # - Ecosystem:
      # - ecosystem/overview.md
      # - ecosystem/friends.md
      # - AIRR-GPT assistant: ecosystem/airr-gpt.md
  # - About:
      # - tutorials/single-cell.qmd

theme:
  name: material
  logo: ../assets/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: blue grey
      accent: amber

    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: indigo
      accent: blue
  features:
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables

plugins:
  - mkquartodocs
  - search:
      lang: en

hooks:
  - hooks.py